config/routes.rb
Rails.application.routes.draw do
  resources :sub_sectors
  resources :sectors
  resources :municipalities
  resources :departments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sub_sector.rb
class SubSector < ApplicationRecord
  belongs_to :Sector
end

app/controllers/sub_sectors_controller.rb
class SubSectorsController < ApplicationController
  before_action :set_sub_sector, only: [:show, :edit, :update, :destroy]

  # GET /sub_sectors
  # GET /sub_sectors.json
  def index
    @sub_sectors = SubSector.all
  end

  # GET /sub_sectors/1
  # GET /sub_sectors/1.json
  def show
  end

  # GET /sub_sectors/new
  def new
    @sub_sector = SubSector.new
  end

  # GET /sub_sectors/1/edit
  def edit
  end

  # POST /sub_sectors
  # POST /sub_sectors.json
  def create
    @sub_sector = SubSector.new(sub_sector_params)

    respond_to do |format|
      if @sub_sector.save
        format.html { redirect_to @sub_sector, notice: 'Sub sector was successfully created.' }
        format.json { render :show, status: :created, location: @sub_sector }
      else
        format.html { render :new }
        format.json { render json: @sub_sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_sectors/1
  # PATCH/PUT /sub_sectors/1.json
  def update
    respond_to do |format|
      if @sub_sector.update(sub_sector_params)
        format.html { redirect_to @sub_sector, notice: 'Sub sector was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_sector }
      else
        format.html { render :edit }
        format.json { render json: @sub_sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_sectors/1
  # DELETE /sub_sectors/1.json
  def destroy
    @sub_sector.destroy
    respond_to do |format|
      format.html { redirect_to sub_sectors_url, notice: 'Sub sector was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_sector
      @sub_sector = SubSector.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_sector_params
      params.require(:sub_sector).permit(:Sector_id, :num_subsector, :description)
    end
end

app/helpers/sub_sectors_helper.rb
module SubSectorsHelper
end

app/views/sub_sectors/_form.html.erb
<%= form_for(sub_sector) do |f| %>
  <% if sub_sector.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sub_sector.errors.count, "error") %> prohibited this sub_sector from being saved:</h2>

      <ul>
      <% sub_sector.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :"Código de Sector" %>
    <%= f.collection_select(:Sector_id, Sector.all, :id, :num_sector) %>
  </div>

  <div class="field">
    <%= f.label :"Código de Sub Sector" %>
    <%= f.text_field :num_subsector %>
  </div>

  <div class="field">
    <%= f.label :Descriptión %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sub_sectors/edit.html.erb
<h1>Modificar Sub Sector</h1>

<%= render 'form', sub_sector: @sub_sector %>

<%= link_to 'Show', @sub_sector %> |
<%= link_to 'Back', sub_sectors_path %>

app/views/sub_sectors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sub Sectores</h1>

<table>
  <thead>
    <tr>
      <th>Código de Sector</th>
      <th>Código Sub Sector</th>
      <th>Descripción</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sub_sectors.each do |sub_sector| %>
      <tr>
        <td><%= sub_sector.Sector.num_sector %></td>
        <td><%= sub_sector.num_subsector %></td>
        <td><%= sub_sector.description %></td>
        <td><%= link_to 'Mostrar', sub_sector %></td>
        <td><%= link_to 'Modificar', edit_sub_sector_path(sub_sector) %></td>
        <td><%= link_to 'Eliminar', sub_sector, method: :delete, data: { confirm: 'Esta Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Sub Sector', new_sub_sector_path %>

app/views/sub_sectors/new.html.erb
<h1>Nuevo Sub Sector</h1>

<%= render 'form', sub_sector: @sub_sector %>

<%= link_to 'Atras', sub_sectors_path %>

app/views/sub_sectors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Código de Sector:</strong>
  <%= @sub_sector.Sector.num_sector %>
</p>

<p>
  <strong>Código de Sub Sector:</strong>
  <%= @sub_sector.num_subsector %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @sub_sector.description %>
</p>

<%= link_to 'Modificar', edit_sub_sector_path(@sub_sector) %> |
<%= link_to 'Atras', sub_sectors_path %>