config/routes.rb
Rails.application.routes.draw do
  resources :sub_sectors
  resources :sectors
  resources :municipalities
  resources :departments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sector.rb
class Sector < ApplicationRecord
  belongs_to :Municipality
  has_many :sub_sectors
end

app/controllers/sectors_controller.rb
class SectorsController < ApplicationController
  before_action :set_sector, only: [:show, :edit, :update, :destroy]

  # GET /sectors
  # GET /sectors.json
  def index
    @sectors = Sector.all
  end

  # GET /sectors/1
  # GET /sectors/1.json
  def show
  end

  # GET /sectors/new
  def new
    @sector = Sector.new
  end

  # GET /sectors/1/edit
  def edit
  end

  # POST /sectors
  # POST /sectors.json
  def create
    @sector = Sector.new(sector_params)

    respond_to do |format|
      if @sector.save
        format.html { redirect_to @sector, notice: 'Sector was successfully created.' }
        format.json { render :show, status: :created, location: @sector }
      else
        format.html { render :new }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sectors/1
  # PATCH/PUT /sectors/1.json
  def update
    respond_to do |format|
      if @sector.update(sector_params)
        format.html { redirect_to @sector, notice: 'Sector was successfully updated.' }
        format.json { render :show, status: :ok, location: @sector }
      else
        format.html { render :edit }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sectors/1
  # DELETE /sectors/1.json
  def destroy
    @sector.destroy
    respond_to do |format|
      format.html { redirect_to sectors_url, notice: 'Sector was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sector
      @sector = Sector.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sector_params
      params.require(:sector).permit(:Municipality_id, :num_sector, :description)
    end
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/views/sectors/_form.html.erb
<%= form_for(sector) do |f| %>
  <% if sector.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sector.errors.count, "error") %> prohibited this sector from being saved:</h2>

      <ul>
      <% sector.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :"Código de Municipio" %>
    <%= f.collection_select(:Municipality_id, Municipality.all, :id, :num_municip) %>
  </div>

  <div class="field">
    <%= f.label :"Código de Sector" %>
    <%= f.text_field :num_sector %>
  </div>

  <div class="field">
    <%= f.label :"Descripción" %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sectors/edit.html.erb
<h1>Modificar Sector</h1>

<%= render 'form', sector: @sector %>

<%= link_to 'Mostrar', @sector %> |
<%= link_to 'Atras', sectors_path %>

app/views/sectors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sectores</h1>

<table>
  <thead>
    <tr>
      <th>Código de Municipio</th>
      <th>Código de Sector</th>
      <th>Descripción</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sectors.each do |sector| %>
      <tr>
        <td><%= sector.Municipality.num_municip %></td>
        <td><%= sector.num_sector %></td>
        <td><%= sector.description %></td>
        <td><%= link_to 'Mostrar', sector %></td>
        <td><%= link_to 'Modificar', edit_sector_path(sector) %></td>
        <td><%= link_to 'Eliminar', sector, method: :delete, data: { confirm: 'Esta Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Sector', new_sector_path %>

app/views/sectors/new.html.erb
<h1>New Sector</h1>

<%= render 'form', sector: @sector %>

<%= link_to 'Atras', sectors_path %>

app/views/sectors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Código de Municipio:</strong>
  <%= @sector.Municipality.num_municip %>
</p>

<p>
  <strong>Código de Sector:</strong>
  <%= @sector.num_sector %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @sector.description %>
</p>

<%= link_to 'Modificar', edit_sector_path(@sector) %> |
<%= link_to 'Atras', sectors_path %>