config/routes.rb
Rails.application.routes.draw do
  resources :sub_sectors
  resources :sectors
  resources :municipalities
  resources :departments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/department.rb
class Department < ApplicationRecord
	has_many :Municipalities
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)
    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:num_depto, :description)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.erb
<%= form_for(department) do |f| %>
  <% if department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% department.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :"Código de Departamento" %>
    <%= f.text_field :num_depto %>
  </div>

  <div class="field">
    <%= f.label :"Descripción" %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Modificar Departamento</h1>

<%= render 'form', department: @department %>

<%= link_to 'Mostrar', @department %> |
<%= link_to 'Atras', departments_path %>

app/views/departments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Departamentos</h1>

<table>
  <thead>
    <tr>
      <th>Código de Departamento</th>
      <th>Descripción</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= department.num_depto %></td>
        <td><%= department.description %></td>
        <td><%= link_to 'Mostar', department %></td>
        <td><%= link_to 'Agregar Municipio', municipalities_path(:department => department) %></td>
        <td><%= link_to 'Modificar', edit_department_path(department) %></td>
        <td><%= link_to 'Eliminar', department, method: :delete, data: { confirm: 'Esta Seguro?' } %></t>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Departamento', new_department_path %>

app/views/departments/new.html.erb
<h1>Nuevo Departamento</h1>

<%= render 'form', department: @department %>

<%= link_to 'Atras', departments_path %>

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Código de Departamento:</strong>
  <%= @department.num_depto %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @department.description %>
</p>

<%= link_to 'Modificar', edit_department_path(@department) %> |
<%= link_to 'Atras', departments_path %>