config/routes.rb
Rails.application.routes.draw do
  resources :sub_sectors
  resources :sectors
  resources :municipalities
  resources :departments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/municipality.rb
class Municipality < ApplicationRecord
  belongs_to :Department
  has_many :Sectors
end

app/controllers/municipalities_controller.rb
class MunicipalitiesController < ApplicationController
  before_action :set_municipality, only: [:show, :edit, :update, :destroy]

  # GET /municipalities
  # GET /municipalities.json
  def index
    @municipalities = Municipality.all
  end

  # GET /municipalities/1
  # GET /municipalities/1.json
  def show
  end

  # GET /municipalities/new
  def new
    @municipality = Municipality.new
  end

  # GET /municipalities/1/edit
  def edit
  end

  # POST /municipalities
  # POST /municipalities.json
  def create
    @municipality = Municipality.new(municipality_params)

    respond_to do |format|
      if @municipality.save
        format.html { redirect_to @municipality, notice: 'Municipality was successfully created.' }
        format.json { render :show, status: :created, location: @municipality }
      else
        format.html { render :new }
        format.json { render json: @municipality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /municipalities/1
  # PATCH/PUT /municipalities/1.json
  def update
    respond_to do |format|
      if @municipality.update(municipality_params)
        format.html { redirect_to @municipality, notice: 'Municipality was successfully updated.' }
        format.json { render :show, status: :ok, location: @municipality }
      else
        format.html { render :edit }
        format.json { render json: @municipality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /municipalities/1
  # DELETE /municipalities/1.json
  def destroy
    @municipality.destroy
    respond_to do |format|
      format.html { redirect_to municipalities_url, notice: 'Municipality was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_municipality
      @municipality = Municipality.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def municipality_params
      params.require(:municipality).permit(:Department_id, :num_municip, :description)
    end
end

app/helpers/municipalities_helper.rb
module MunicipalitiesHelper
end

app/views/municipalities/_form.html.erb
<%= form_for(municipality) do |f| %>
  <% if municipality.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(municipality.errors.count, "error") %> prohibited this municipality from being saved:</h2>

      <ul>
      <% municipality.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="visible:false">
    <%= f.text_field :Department_id, :value => params[:kk], :hidden => true %>
  </div>

  <div class="field">
    <%= f.label :"Código de Municipio" %>
    <%= f.text_field :num_municip %>
  </div>

  <div class="field">
    <%= f.label :"Descripción" %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/municipalities/edit.html.erb
<h1>Modificar Municipio</h1>

<%= render 'form', municipality: @municipality %>

<%= link_to 'Mostrar', @municipality %> |
<%= link_to 'Atras', municipalities_path %>

app/views/municipalities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Municipios de <%= Department.find(params[:department]).num_depto %></h1>

<table>
  <thead>
    <tr>
      <th>Departamento</th>
      <th>Código de Municipio</th>
      <th>Descripción</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @municipalities.where(Department: params[:department]).each do |municipality| %>
      <!--% @municipalities.where("Department.id = ?", params[:d_id]) do |municipality| %-->
      <tr>
        <script>
          console.log(<%= municipality.Department.id %>)
        </script>
        <td><%= municipality.Department.num_depto %></td>
        <td><%= municipality.num_municip %></td>
        <td><%= municipality.description %></td>
        <td><%= link_to 'Mostrar', municipality %></td>
        <td><%= link_to 'Modificar', edit_municipality_path(municipality) %></td>
        <td><%= link_to 'Eliminar', municipality, method: :delete, data: { confirm: 'Esta Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Municipio', new_municipality_path(:kk => params[:department]) %>

app/views/municipalities/new.html.erb
<h1>New Municipality</h1>

<%= render 'form', municipality: @municipality %>

<%= link_to 'Atras', municipalities_path %>

app/views/municipalities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Código de Departamento:</strong>
  <%= @municipality.Department.num_depto %>
</p>

<p>
  <strong>Código de Municipio:</strong>
  <%= @municipality.num_municip %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @municipality.description %>
</p>

<%= link_to 'Modificar', edit_municipality_path(@municipality) %> |
<%= link_to 'Atras', municipalities_path %>